//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WorldTime2000.rc
//
#define IDC_SNOOZE                      2
#define ID_DETAILS                      3
#define IDC_UPDATER_START               3
#define IDD_ABOUTBOX                    100
#define IDD_SKINDIALOG_DIALOG           102
#define IDR_MAINFRAME                   128
#define IDR_WORLDTTYPE                  129
#define IDI_ICON1                       130
#define IDI_ICON2                       131
#define IDI_WORLD                       131
#define IDI_ICON3                       132
#define IDD_HOME                        133
#define IDD_FEATURES                    135
#define IDD_ADD_DISPLAY                 136
#define IDI_ALARM1                      137
#define IDI_SUN                         138
#define IDD_ADD_LOCATION                138
#define IDI_WORLD2                      141
#define IDI_DISPLAY1                    141
#define IDI_WORLD3                      142
#define IDD_PREFERENCES                 142
#define IDI_LOCATIONS                   142
#define IDI_EARTH                       144
#define IDI_ICON7                       145
#define IDI_LOCATION                    145
#define IDI_MEMBER                      146
#define IDI_ICON8                       147
#define IDI_HELP                        147
#define IDD_ALARM_MESSAGE               149
#define IDI_LOCATION_SMALL              152
#define IDI_ICON12                      153
#define IDI_ICON13                      154
#define IDI_ICON14                      155
#define IDI_ICON15                      156
#define IDI_ICON16                      159
#define IDI_ICON4                       160
#define IDI_ICON5                       161
#define IDI_ICON6                       162
#define IDI_ANIM9                       189
#define IDI_ANIM18                      190
#define IDI_ANIM19                      191
#define IDB_BITMAP1                     191
#define IDI_ANIM2                       192
#define IDI_ANIM20                      193
#define IDI_ANIM21                      194
#define IDI_ANIM22                      195
#define IDI_ANIM23                      196
#define IDI_ANIM24                      197
#define IDI_ANIM3                       198
#define IDI_ANIM4                       199
#define IDI_ANIM10                      200
#define IDI_ANIM5                       201
#define IDI_ANIM6                       202
#define IDI_ANIM7                       203
#define IDI_ANIM8                       204
#define IDI_ANIM11                      205
#define IDI_ANIM12                      206
#define IDI_ANIM13                      207
#define IDI_ANIM14                      208
#define IDI_ANIM15                      209
#define IDI_ANIM16                      210
#define IDI_ANIM17                      211
#define IDI_ANIM1                       212
#define IDI_ANIM164                     213
#define IDI_DST                         214
#define IDI_HOME                        214
#define IDI_DSTON                       215
#define IDI_DSTOFF                      216
#define IDD_DETAILS                     217
#define IDI_ALARM                       217
#define IDD_DELETE                      218
#define IDD_MODIFY2                     219
#define IDD_ALARM                       220
#define IDD_REGISTER                    221
#define IDD_ADD_DISPLAY1                222
#define IDD_ADD_MODIFY                  222
#define IDD_MODIFY                      222
#define IDR_HTML1                       223
#define IDD_LEGEND                      223
#define IDR_JPG1                        224
#define IDD_WHATIF                      224
#define IDR_JPG2                        225
#define IDD_PREFERENCES1                225
#define IDR_HISTORY                     226
#define IDR_FEATURES                    227
#define IDR_ABOUT                       228
#define IDD_LOCATIONS                   229
#define IDD_MEMBERS                     230
#define IDD_MEMBER_ADD                  231
#define IDD_LOCATION_DETAILS            233
#define IDD_PREFERENCES_SOUNDS          234
#define IDD_PREFERENCES_TEMPLATE        235
#define IDD_PREFERENCES_TIME            237
#define IDB_FILE_ADD                    238
#define IDD_PREFERENCES_DISPLAY         238
#define IDR_HELP                        239
#define IDR_CONTEXT                     242
#define IDR_PREFERENCES                 243
#define IDD_ALARMS                      243
#define IDR_DOCUMENTATION               244
#define IDD_UPDATER                     244
#define IDR_ORDER                       245
#define IDR_SYSTEMTRAY                  245
#define IDB_SANDSTONE                   246
#define IDB_TOOLBAR_HOT                 256
#define IDI_ICON9                       257
#define IDI_ADD                         257
#define IDI_ICON18                      261
#define IDI_ICON11                      262
#define IDI_PREFERENCES                 262
#define IDI_ICON19                      263
#define IDI_DOCS                        263
#define IDI_ICON20                      264
#define IDI_DISPLAY                     264
#define IDI_ICON21                      265
#define IDI_HOMELOCATION                265
#define IDI_ICON22                      266
#define IDI_ALARMOFF                    266
#define IDI_ICON23                      267
#define IDI_ICON24                      268
#define IDI_ICON25                      269
#define IDI_TRAY                        270
#define IDR_FRAME                       270
#define IDI_MODIFY                      271
#define IDR_CONTENTS                    271
#define IDI_ICON17                      272
#define IDI_BASEICON                    272
#define IDI_DELETE                      273
#define IDI_DSTON1                      274
#define IDI_DSTON2                      275
#define IDI_DSTON3                      276
#define IDI_LEGEND                      277
#define IDI_WHATIF                      278
#define IDI_MEMBER_SMALL                279
#define IDI_UPDATER                     280
#define IDR_MAINFRAME1                  281
#define IDD_ALARMold                    282
#define IDI_TRAY1                       282
#define IDI_ALARM2                      283
#define IDI_HOME1                       284
#define IDI_DSTON4                      285
#define IDI_WHATIF1                     286
#define IDI_TIME1                       287
#define IDI_TIME2                       288
#define IDI_TIME3                       289
#define IDI_TIME4                       290
#define IDI_TIME5                       291
#define IDI_TIME6                       292
#define IDI_TIME7                       293
#define IDI_TIME8                       294
#define IDI_TIME9                       295
#define IDI_TIME10                      296
#define IDI_TIME11                      297
#define IDI_TIME12                      298
#define IDI_TIME13                      299
#define IDI_TIME14                      300
#define IDB_BITMAP2                     302
#define IDB_BITMAP3                     303
#define IDB_BITMAP4                     304
#define IDB_BITMAP5                     305
#define IDB_BITMAP6                     306
#define IDB_BITMAP7                     307
#define IDB_BITMAP8                     308
#define IDB_BITMAP9                     309
#define IDB_BITMAP10                    310
#define IDB_BITMAP11                    311
#define IDB_BITMAP12                    312
#define IDB_TOOLBAR_COLD                313
#define IDB_PREFERENCES                 314
#define IDB_HELP                        315
#define IDB_FONTS                       316
#define IDB_ALARMS                      317
#define IDB_HOME                        318
#define IDB_DISPLAY                     319
#define IDB_LOCATIONS                   320
#define IDB_SKINS                       321
#define IDB_BACKGROUND                  322
#define IDB_FILE_ADDTODISPLAY           325
#define IDB_FILE_MODIFY                 326
#define IDB_FILE_DELETE                 327
#define IDB_FILE_HOME                   328
#define IDB_APP_EXIT                    329
#define IDB_HELP_CONTENTS               330
#define IDB_FILE_ALARMRESET             331
#define IDC_ALARM_APPNAME               1001
#define IDC_EDIT1                       1004
#define IDC_ALARM_MESSAGE               1004
#define IDC_MEMBER_ADD_EMAIL            1004
#define IDC_LOC_DETAILS_NAME            1004
#define IDC_SLIDER1                     1005
#define IDC_MEMBER_ADD_PHONE            1005
#define IDC_LOC_DETAILS_DSTOFFSET       1005
#define IDC_EDIT2                       1006
#define IDC_LOC_DETAILS_COUNTRY         1006
#define IDC_ADD_HOURS                   1007
#define IDC_ADD_DISPLAY_LIST            1008
#define IDC_EDIT3                       1008
#define IDC_LOC_DETAILS_COUNTRYCODE     1008
#define IDC_CHECK1                      1009
#define IDC_ALARM_RUNAPP                1009
#define IDC_PREFERENCES_TOPMOST         1009
#define IDC_LOC_DETAILS_DST             1009
#define IDC_CHECK2                      1010
#define IDC_EDIT4                       1010
#define IDC_LOCATION_LIST               1010
#define IDC_LOC_DETAILS_AREACODE        1010
#define IDC_PREFERENCES_TOOLTIPS        1010
#define IDC_ADD_START_DAY               1011
#define IDC_CHECK4                      1011
#define IDC_LIST                        1011
#define IDC_LOC_DETAILS_START_DAY       1011
#define IDC_ADD_START_FIRSTLAST         1012
#define IDC_CHECK5                      1012
#define IDC_ALARMS_ADD                  1012
#define IDC_LOC_DETAILS_START_FIRSTLAST 1012
#define IDC_ADD_START_MONTH             1013
#define IDC_CHECK6                      1013
#define IDC_ALARMS_REMOVE               1013
#define IDC_LOC_DETAILS_START_MONTH     1013
#define IDC_ADD_END_DAY                 1014
#define IDC_ALARMS_PROPERTIES           1014
#define IDC_LOC_DETAILS_END_DAY         1014
#define IDC_ADD_END_FIRSTLAST           1015
#define IDC_DETAILS1                    1015
#define IDC_CHECK8                      1015
#define IDC_ALARM_TIME                  1015
#define IDC_LOC_DETAILS_END_FIRSTLAST   1015
#define IDC_ADD_END_MONTH               1016
#define IDC_ALARM_DATE                  1016
#define IDC_LOC_DETAILS_END_MONTH       1016
#define IDC_DETAILS2                    1017
#define IDC_CUSTOM1                     1017
#define IDC_LOC_DETAILS_LATDEGREES      1017
#define IDC_DETAILS3                    1018
#define IDC_MODIFY_LIST                 1018
#define IDC_LOC_DETAILS_LATNS           1018
#define IDC_DETAILS4                    1019
#define IDC_HOME_COLOR                  1019
#define IDC_ALARM_RECURRING             1019
#define IDC_MEMBER_ADD_NAME             1019
#define IDC_LOC_DETAILS_LONGNS          1019
#define IDC_DETAILS5                    1020
#define IDC_LOCATION_COLOR              1020
#define IDC_LOC_DETAILS_LONGDEGREES     1020
#define IDC_SELECTED_COLOR              1021
#define IDC_ALARM_PLAYSOUND             1021
#define IDC_MEMBER_ADD                  1021
#define IDC_ADD_HOURS2                  1021
#define IDC_BACKGROUND_COLOR            1022
#define IDC_MEMBER_REMOVE               1022
#define IDC_BACKGROUND_TEXTURE          1023
#define IDC_PROPERTIES_USETEMPLATE      1023
#define IDC_MEMBER_PROPERTIES           1023
#define IDC_HOME_SAMPLE                 1024
#define IDC_MEMBER_ADD_LOCATION         1024
#define IDC_ALARMMESSAGE                1024
#define IDC_SELECTED_SAMPLE             1025
#define IDC_HOUR                        1025
#define IDC_ALARM_DETAILS               1025
#define IDC_LOCATION_SAMPLE             1026
#define IDC_MINUTE                      1026
#define IDC_ABOUT_COMMENTS              1026
#define IDC_BACKGROUND_SAMPLE           1027
#define IDC_ENABLE                      1027
#define IDC_LOCATION                    1028
#define IDC_ABOUT_WEBSITE               1028
#define IDC_REGISTER_NAME               1029
#define IDC_ABOUT_TITLE                 1029
#define IDC_REGISTER_KEY                1030
#define IDC_CHECK3                      1030
#define IDC_MEMBER_LIST                 1031
#define IDC_CONNECT_STATUS              1031
#define IDC_MEMBER_ADD_LOCONLY          1032
#define IDC_DATETIMEPICKER1             1036
#define IDC_LIST1                       1037
#define IDC_PREFERENCES_SHOWAM          1038
#define IDC_PREFERENCES_24HOUR          1039
#define IDC_PREFERENCES_SECONDS         1040
#define IDC_AMPM                        1045
#define IDC_SOUNDALARM                  1046
#define IDC_SOUNDHOUR                   1047
#define IDC_SOUNDQUARTER                1048
#define IDC_SOUNDALARMON                1049
#define IDC_SOUNDHOURON                 1050
#define IDC_SOUNDQUARTERON              1051
#define IDC_DELETE                      1051
#define IDC_LOCATION_ADD                1051
#define IDC_LOCATION_REMOVE             1052
#define IDC_BUTTON1                     1053
#define IDC_ALARM_CHOOSEAPP             1053
#define IDC_ALARM_TEST                  1053
#define IDC_UPDATE                      1053
#define IDC_LOCATION_PROPERTIES         1053
#define IDC_APP_NAME                    1054
#define IDC_HOUR_TEST                   1054
#define IDC_QUARTER_TEST                1055
#define IDC_DATE                        1056
#define IDC_TIME                        1057
#define IDC_SKIN                        1058
#define IDC_MESSAGE                     1061
#define IDC_ALARMSOUND_FILE             1063
#define IDC_HOURSOUND_FILE              1064
#define IDC_QUARTERSOUND_FILE           1065
#define IDC_PREFERENCES_BACKGROUNDCOLOR 1065
#define IDC_PREFERENCES_LOADWALLPAPER   1066
#define IDC_PREFERENCES_SHOWWALLPAPER   1067
#define IDC_PREFERENCES_WALLPAPERNAME   1068
#define IDC_COMBO1                      1069
#define IDC_PROPERTIES_TEMPLATE         1072
#define IDC_PROPERTIES_TEMPLATE2        1073
#define IDC_PROPERTIES_TEMPLATE3        1074
#define IDC_LOCATION_LOCATIONICON       1091
#define IDC_LOCATION_PERSONICON         1092
#define ID_FILE_HOME                    32771
#define ID_FILE_ADD                     32773
#define ID_HELP_FUTURE                  32775
#define ID_FILE_ADDTODISPLAY            32776
#define ID_FILE_PREFERENCES             32778
#define ID_FILE_DELETE                  32780
#define ID_FILE_MODIFY                  32781
#define ID_BUTTON32782                  32782
#define ID_HELP_CONTENTS                32784
#define ID_SHOW_TOOLBAR                 32785
#define ID_SHOW_STATUS_BAR              32786
#define ID_FILE_ALARM                   32792
#define ID_FILE_ALARMRESET              32793
#define ID_CONTEXT_DELETE               32794
#define ID_CONTEXT_MODIFY               32795
#define ID_REGISTER                     32796
#define ID_FILE_FONT                    32797
#define ID_ORDER                        32798
#define ID_CONTEXT_MOVE                 32799
#define ID_TIMESYNC                     32802
#define ID_TRAY_OPEN                    32803
#define ID_APP_OPEN                     32803
#define ID_SORT_NAME                    32808
#define ID_SORT_COUNTRY                 32809
#define ID_SORT_TIME                    32810
#define ID_VIEW_GMT                     32811
#define ID_HELP_LEGEND                  32812
#define ID_CONTEXT_WHATIF               32813
#define ID_VIEW_WHATIFMODE              32814
#define ID_VIEW_WHATIF                  32815
#define ID_FILE_LOADSKIN                32816
#define ID_FILE_REMOVESKIN              32817
#define ID_CONTEXT_FONT                 32818
#define ID_FILE_ALARMS                  32819
#define ID_FILE_LOCAIONS                32820
#define ID_FILE_LOCATIONS               32821
#define IDS_REGROOT                     61204

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        288
#define _APS_NEXT_COMMAND_VALUE         32824
#define _APS_NEXT_CONTROL_VALUE         1070
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
