//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by WorldTime2000.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_WORLDTTYPE                  129
#define IDI_ICON1                       130
#define IDI_ICON2                       131
#define IDI_ICON3                       132
#define IDD_HOME                        133
#define IDD_ADD                         134
#define IDI_ICON4                       134
#define IDI_ICON5                       135
#define IDD_FEATURES                    135
#define IDI_ICON6                       136
#define IDD_ADD_DISPLAY                 136
#define IDC_HOME_LIST                   1001
#define IDC_EDIT1                       1004
#define IDC_SLIDER1                     1005
#define IDC_ADD_HOURS                   1007
#define IDC_ADD_DISPLAY_LIST            1008
#define ID_FILE_HOME                    32771
#define ID_FILE_ADD                     32773
#define ID_HELP_FUTURE                  32775
#define ID_FILE_ADDTODISPLAY            32776

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1009
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
